# run: conda env create --file environment.yml
name: audiomocap
channels:
- conda-forge
- defaults
dependencies:
- python==3.8
- nb_conda_kernels==2.3.1
# add here more dependencies which you use, preferably WITH version!
# - anaconda
# - pip
- numpy==1.22.2
- pip:
  - notebook
  - pyrealsense2==2.50.0.3812
  - opencv-python==4.5.5.62
  - mediapipe==0.8.9.1 
#   - matplotlib==2.0.0
